### ISSUE TITLE
Docker 环境下，FastDFS Tracker 必须使用 Host 网络

### ISSUE THREAD

**Issue by ganpengyu** [happyfish100/fastdfs#224]
制作了 FastDFS 镜像，里面包含 Tracker 和 Storage 以及 Nginx。启动 FastDFS 容器后，将其注册到和业务系统相同的网络上，业务系统无法使用 容器名称或容器 IP 连上 Tracker。只有将 FastDFS 容器设置为使用宿主机网络，然后让业务系统使用宿主机 IP 才能连上 Tracker。我参考了多个 dockerhub 上高 stars 的镜像，都是要求容器使用宿主机网络，请问这是为什么？

**Comment by junxchen** [comment]
我也遇见一样的问题，请问您是这么解决的 谢谢

**Comment by jingjingxyk** [comment]
docker-compose , kubernetes  服务发发现 概念了解一下! 使用服务名访问 

Tracker 和 Storage 放在单独的容器里.

**Comment by jingjingxyk** [comment]
# kubernetes  nfs(提供持久化)  fastdfs   
> 要改造一下和ETCD结合起来就会更方便

## k8s 里部署在fastdfs  
### fastdfs-tracker-nfs-pv
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastdfs-tracker-nfs-pv
  labels:
    pv: fastdfs-tracker-nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
  - soft
  - nfsvers=4.1
  nfs:
    server: 192.168.1.10
    path: "/data/jingjingxyk/fastdfs-data/"
```

###fastdfs-tracker-nfs-pvc
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastdfs-tracker-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv: fastdfs-tracker-nfs-pv
  resources:
    requests:
      storage: 5Gi
```

###fastdfs-tracker-service
```
kind: Service
apiVersion: v1
metadata:
  name: fastdfs-tracker-service
spec:
  selector:
    app: fastdfs-tracker-pod
  ports:
  - name: fastdfs-tracker
    protocol: TCP
    port: 22122
    targetPort: 22122
#  clusterIP: None
```

###fastdfs-tracker-satefulset

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastdfs-tracker-satefulset
spec:
  selector:
    matchLabels:
      app: fastdfs-tracker-pod
  serviceName: "fastdfs-tracker-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: fastdfs-tracker-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      -   name: fastdfs-tracker
          image: registry.cn-hangzhou.aliyuncs.com/jingjingxyk/fastdfs:latest
          ports:
          - containerPort: 22122
          command: #[ "echo", "SUCCESS" ]
          - /bin/sh
          - -c
          - |
            /usr/bin/fdfs_trackerd /etc/fdfs/tracker.conf && tail -f /dev/null
          volumeMounts:
          - name: fastdfs-config
            mountPath: "/etc/fdfs"
          - name: fastdfs-data
            mountPath: "/www/"

      volumes: #卷配置
      - name: fastdfs-config
        persistentVolumeClaim:
          claimName: fastdfs-nfs-pvc
      - name: fastdfs-data
        persistentVolumeClaim:
          claimName: fastdfs-tracker-nfs-pvc

      imagePullSecrets:
      - name: jingjingxyk-docker-secret


```
###fastddfs 导入 k8s 使用作为一个服务使用,  使用 Endpoints资源
``` 
kind: Endpoints
apiVersion: v1
metadata:
  name: fastdfs-tracker-endpoint
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.156 #fastdfs-tracker的ip
  ports:
  - port: Endpoints


```
