### ISSUE TITLE
用docker安装后 storage的IP地址映射宿主地址问题

### ISSUE THREAD

**Issue by kiritoowo** [happyfish100/fastdfs#336]
storage的地址是docker虚拟网卡的地址
无法获取服务端连接资源：can't create connection to 172.17.0.1:23000

**Comment by tangxiaonian** [comment]
这个怎么解决的，，我也遇到了！！！

**Comment by kiritoowo** [comment]
使用了一个指令，让容器直接映射本机端口 --network=host

**Comment by tangxiaonian** [comment]
ok ,谢谢了

**Comment by dezhenglu** [comment]
请问有没有其他解决方案啊? 这样一来每次都要改conf的

**Comment by kiritoowo** [comment]
可以使用docker network create somenetwork 创建网络并进行统一设置，不过启动的时候也需要加入--net somenetwork指定自定义网络 ，可以参考官方文档进行自定义设置，官方文档地址：https://docs.docker.com/engine/reference/commandline/network_create/

**Comment by wujushan** [comment]
可以试下使用`overlay`网络模式或者双网卡的模式`bridge+overlay`。在storage_ids.conf里面使用服务名。

docker-compose.yml
```yaml
version: '3'
services:
   webservice:
     networks:
       - frontend
   apiservice:
     networks:
       - frontend
       - backend
   fdfs-tracker0:
     networks:
       - backend
    fdfs-tracker1:
      networks:
       - backend
    fdfs-storage0:
      networks:
       - backend
    fdfs-storage1:
      networks:
       - backend
networks:
# frontend网络用于服务的互相通信
  frontend:
    driver: bridge
# backend网络用于fdfs的tracker storage和client互相通信
  backend:
    driver: overlay
```
storage_ids.conf
```
10001 group1 fdfs-storage0
10002 group1 fdfs-storage1
```
storage.conf
```
tracker_server=fdfs-tracker0:22122
tracker_server=fdfs-tracker1:22122
```
